### ISSUE TITLE
After I enter the recepient name and message I am getting this error

### ISSUE THREAD

**Issue by Chitturiarunkrishna** [Dibyajitdj/WhatsappPost#1]

**Comment by Chitturiarunkrishna** [comment]
Traceback (most recent call last):
  File "main.py", line 76, in <module>
    menu()
  File "main.py", line 55, in menu
    sch=driver.find_element_by_class_name('_2zCfw')
  File "C:\Users\chitt\AppData\Roaming\Python\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 564, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "C:\Users\chitt\AppData\Roaming\Python\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\chitt\AppData\Roaming\Python\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\chitt\AppData\Roaming\Python\Python38\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: ._2zCfw

**Comment by Chitturiarunkrishna** [comment]
I am using geckodriver

**Comment by DibyajitTripathy** [comment]
scan the Whatsapp web and keep it open before entering any recipient name and message

**Comment by Chitturiarunkrishna** [comment]
Yeah I did it
![image](https://user-images.githubusercontent.com/36875148/82150784-a7fa8f00-9876-11ea-8bb5-32a5fb62f845.png)
Still facing it
